app/routes.php
<?php
# Home
Route::get('/', ['before'=>'auth','as'=>'home', 'uses'=>'SiteController@index']);
# Login
Route::get('login', ['as'=>'user.login', 'before'=>'already', 'uses'=>'UsersController@get_login']);
Route::post('login', ['as'=>'user.post.login', 'uses'=>'UsersController@post_login']);
Route::get('logout', ['as'=>'user.logout', 'uses'=>'UsersController@logout']);
# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);
# Cadastro
Route::get('cadastro', ['as'=>'user.register', 'uses'=>'UsersController@get_register']);
Route::post('cadastro', ['as'=>'user.post.register', 'uses'=>'UsersController@post_register']);
Route::get('coord', 'CustomersController@coord');
# Clientes
Route::any('clientes', 'CustomersController@getCustomers');
Route::post('clientes-concorrentes', 'CustomersController@companyClientsUpload');
# Administração
Route::group(['prefix'=>'admin','before'=>'auth|admin'], function(){
	
	Route::resource('clientes', 'CustomersController');
	
	Route::get('concorrentes', ['as'=>'admin.concorrentes.index', 'uses'=>'CustomersController@index']);
	
	Route::resource('empresas', 'CompaniesController');

	Route::resource('usuarios', 'UsersController');
	
	Route::resource('grupoprodutos', 'ProdgroupsController');

	# Upload clientes Knauf
	Route::post('upload/clientes/knauf',['as'=>'customers.upload', 'uses'=>'CustomersController@clientUpload']);
	Route::post('upload/concorrentes/knauf',['as'=>'concorrentes.upload', 'uses'=>'CustomersController@companyClientsUpload']);
	
	Route::get('aprovar', ['as'=>'admin.approve.user', 'uses'=>'UsersController@approve']);

	Route::get('mapa', 'CustomersController@mapa');

	Route::resource('vendas','TransactionsController');
	Route::post('upload/vendas',['as'=>'transaction.upload', 'uses'=>'TransactionsController@upload']);

	Route::get('set-coord/{num_ini?}/{num_fim?}', 'CustomersController@setCoords');
});

app/models/Prodgroup.php
<?php

class Prodgroup extends \Eloquent {
	
	protected $table = 'product_groups';

	protected $fillable = ['name'];

	public static $rules = ['name'=>'required'];

	public function getAccept()
	{
		return unserialize($this->accept);
	}
}

app/controllers/ProdgroupsController.php
<?php 
/**
* Crud de grupo de produtos
*/
class ProdgroupsController extends BaseController
{
	public function index()
	{
		$prodgroups = Prodgroup::orderBy('id','desc')->paginate(20);
		return View::make('admin.prodgroups.index',compact('prodgroups'));
	}	
	public function create()
	{
		return View::make('admin.prodgroups.create');
	}
	public function store()
	{
		$data = Input::all();

		$prodgroup = Prodgroup::create($data);
		$prodgroup->accept = serialize($data['accept']);
		$prodgroup->save();

		return Redirect::route('admin.grupoprodutos.index')->withSuccess('Criado com sucesso');
	}
	public function edit($id)
	{
		$prodgroup = Prodgroup::find($id);
		return View::make('admin.prodgroups.edit', compact('prodgroup'));
	}
	public function update($id)
	{
		$data = Input::all();
		
		$prodgroup = Prodgroup::find($id);

		$prodgroup->update($data);
		$prodgroup->accept = serialize($data['accept']);
		$prodgroup->save();

		return Redirect::route('admin.grupoprodutos.edit', $prodgroup->id)->withSuccess('Editado com sucesso');
	}
	public function destroy($id)
	{
		$prodgroup = Prodgroup::find($id);
		
		$prodgroup->delete();

		return Redirect::route('admin.grupoprodutos.index')->withSuccess('Apagado com sucesso');
	}
}

app/views/admin/prodgroups/create.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Novo grupo de produtos</h1>
	
	<div class="row">
		<div class="col-md-8">
		@include('partials.notifications')
		{{ Form::open(['route'=>'admin.grupoprodutos.store']) }}
		
			<div class="form-group">
		      <label for="email">Nome</label>
		      {{ Form::text('name', null, ['class'=>'form-control']) }}
		    </div>
		    <div class="form-group">
		      <label for="accept">Ids separados por virgula</label>
		      {{ Form::textarea('accept', null, ['class'=>'form-control']) }}
		    </div>
		     <div class="form-group text-right">
		      <label for=""></label>
		      {{ Form::submit('Enviar',  ['class'=>'btn btn-primary']) }}
		    </div>
		  
		{{ Form::close() }}
		<span class="pull-right">
			<a class="link" href=""><i class="fa fa-arrow-left"></i>Voltar</a>
		</span>
		</div>
		
	</div>
@stop

app/views/admin/prodgroups/edit.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Editar grupo de produtos</h1>
	
	<div class="row">
		<div class="col-md-8">
		@include('partials.notifications')
		{{ Form::open(['route'=>array('admin.grupoprodutos.update', $prodgroup->id), 'method'=>'put']) }}
		
			<div class="form-group">
		      <label for="email">Nome</label>
		      {{ Form::text('name', $prodgroup->name, ['class'=>'form-control']) }}
		    </div>
		    <div class="form-group">
		      <label for="accept">Ids separados por virgula</label>
		      {{ Form::textarea('accept', $prodgroup->getAccept(), ['class'=>'form-control']) }}
		    </div>
		     <div class="form-group text-right">
		      <label for=""></label>
		      {{ Form::submit('Atualizar',  ['class'=>'btn btn-primary']) }}
		    </div>
		  
		{{ Form::close() }}
		<span class="pull-right">
			<a class="link" href=""><i class="fa fa-arrow-left"></i>Voltar</a>
		</span>
		</div>
		
	</div>
@stop

app/views/admin/prodgroups/index.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Grupo de produtos <small>({{ $prodgroups->getTotal() }})</small></h1>
	<div class="row">
		<div class="col-md-12">
			<a class="btn btn-primary" href="{{ route('admin.grupoprodutos.create') }}">novo <i class="fa fa-plus"></i></a>
		</div>
	</div>
	@include('partials.notifications')
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-bordered">
				<tr>
					<th>Nome</th>
					<th>Aceita Ids</th>
					<th>Editar</th>
					<th>Apagar</th>
				</tr>
				@foreach($prodgroups as $g)
				<tr>
					<td>{{ $g->name }}</td>
					<td>{{ $g->getAccept() }}</td>
					<td><a class="btn btn-info" href="{{ route('admin.grupoprodutos.edit', $g->id) }}"><i class="fa fa-edit"></i></a></td>
					<td>
						{{ Form::open(['route'=>array('admin.grupoprodutos.destroy', $g->id), 'method'=>'delete']) }}

						{{ Form::button('<i class="fa fa-trash"></i>', ['type'=>'submit']) }}
						{{ Form::close() }}
					</td>
				
				</tr>
				@endforeach
			</table>
			{{ $prodgroups->appends($_GET)->links() }}
		</div>
	</div>
@stop