app/routes.php
<?php
# Home
Route::get('/', ['before'=>'auth','as'=>'home', 'uses'=>'SiteController@index']);
# Login
Route::get('login', ['as'=>'user.login', 'before'=>'already', 'uses'=>'UsersController@get_login']);
Route::post('login', ['as'=>'user.post.login', 'uses'=>'UsersController@post_login']);
Route::get('logout', ['as'=>'user.logout', 'uses'=>'UsersController@logout']);
# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);
# Cadastro
Route::get('cadastro', ['as'=>'user.register', 'uses'=>'UsersController@get_register']);
Route::post('cadastro', ['as'=>'user.post.register', 'uses'=>'UsersController@post_register']);
Route::get('coord', 'CustomersController@coord');
# Clientes
Route::any('clientes', 'CustomersController@getCustomers');
Route::post('clientes-concorrentes', 'CustomersController@companyClientsUpload');
# Administração
Route::group(['prefix'=>'admin','before'=>'auth|admin'], function(){
	
	Route::resource('clientes', 'CustomersController');
	
	Route::get('concorrentes', ['as'=>'admin.concorrentes.index', 'uses'=>'CustomersController@index']);
	
	Route::resource('empresas', 'CompaniesController');

	Route::resource('usuarios', 'UsersController');
	
	Route::resource('grupoprodutos', 'ProdgroupsController');

	# Upload clientes Knauf
	Route::post('upload/clientes/knauf',['as'=>'customers.upload', 'uses'=>'CustomersController@clientUpload']);
	Route::post('upload/concorrentes/knauf',['as'=>'concorrentes.upload', 'uses'=>'CustomersController@companyClientsUpload']);
	
	Route::get('aprovar', ['as'=>'admin.approve.user', 'uses'=>'UsersController@approve']);

	Route::get('mapa', 'CustomersController@mapa');

	Route::resource('vendas','TransactionsController');
	Route::post('upload/vendas',['as'=>'transaction.upload', 'uses'=>'TransactionsController@upload']);

	Route::get('set-coord/{num_ini?}/{num_fim?}', 'CustomersController@setCoords');
});

app/controllers/TransactionsController.php
<?php

class TransactionsController extends BaseController {
	protected $layout = 'layouts.application';

	public function index()
	{
		$transactions = Transaction::orderBy('id','desc')->paginate(30);

		return View::make('admin.transactions.index', compact('transactions'));
	}

	public function create()
	{

	}

	public function edit($id)
	{
		$transaction = Transaction::find($id);
	}

	public function destroy($id)
	{
		$transaction = Transaction::find($id);
	}

	public function upload()
	{
		if(!File::isFile(Input::file('transactions'))){
			
			//print_r(Input::file('transactions'));
			return Redirect::route('admin.vendas.index')->withError('Necessário subir um arquivo .xslx válido');
		}

		$file = Input::file('transactions');
		$ext = $file->getClientOriginalExtension();
        $name = 'arquivoconsumo';
        $filename = $name.'.'.$ext;

        if(File::exists('uploads/vendas', $filename)){
        	File::delete('uploads/vendas', $filename);
        }
        
		$file->move('uploads/vendas', $filename);

		Excel::load('uploads/vendas/'.$filename, function($reader) {

		    $results = $reader->all();

		    //print($results);

			foreach ($results as $row) {
				$t = Transaction::where('no_documento',$row->no_documento)->first();
				if(isset($t->id)){
					// Edita
					$transaction = $t;
				}else{
					// Cria
					$transaction = new Transaction;
				}
				$transaction->no_documento = $row->no_documento;
				$transaction->customer_id = $row->cliente;
				$transaction->artigo = $row->artigo;
				$transaction->receita = $row->receita;
				$transaction->qtd_vendas = $row->qtd_vendas;
				$transaction->prod_hierarquia = $row->hierarq_produtos;
				$transaction->prod_group = $row->main_item_group;
				$transaction->prod_desc = $row->descricao_artigo;
				$transaction->customer_group = $row->grupo_de_clientes;
				$transaction->quantidade_de_vendas = $row->quantidade_de_vendas;
				$transaction->um_basica_qtdvendas = $row->um_basica_qtdvendas;
				$transaction->sales_rep = $row->sales_represent;
				$transaction->transaction_at = $row->data_da_fatura;
				$transaction->save();
				//echo $row->data_da_fatura.'<br/>';
			}

		});
		return Redirect::route('admin.vendas.index')->withSuccess('Vendas atualizadas com sucesso');
	}
}

app/views/admin/transactions/index.blade.php
@extends('layouts.admin')
@section('content')
	<h1>Vendas <small>({{ $transactions->getTotal() }})</small></h1>
	
	@include('admin.transactions.upload')
	<div class="row">
		<div class="col-md-12">
		
			<table class="table table-striped table-bordered">
				<tr>
					
					<th>Nome cliente</th>
					<th>Descrição</th>
					<th>Editar</th>
					<th>Apagar</th>
				</tr>
				@foreach($transactions as $t)
				<tr>
					<td>{{ isset($t->customer->id) ? $t->customer->Nome : null }}</td>
					<td>{{ $t->prod_desc }}</td>
					<td><a class="btn btn-info" href="{{ route('admin.vendas.edit', $t->id) }}"><i class="fa fa-edit"></i></a></td>
					<td>
						{{ Form::open(['route'=>array('admin.vendas.destroy', $t->id), 'method'=>'delete']) }}
						{{ Form::button('<i class="fa fa-trash"></i>', ['class'=>'btn btn-danger', 'type'=>'submit']) }}
						{{ Form::close() }}
					</td>
					
				</tr>
				@endforeach
			</table>
			{{ $transactions->appends($_GET)->links() }}
		</div>
	</div>
@stop

app/views/admin/transactions/upload.blade.php
<div class="row">
	<div class="col-md-12">
	@include('partials.notifications')
		<div class="row">
			<div class="col-md-8">
				{{ Form::open(['route'=> 'transaction.upload', 'class'=>'form-inline frm_up', 'files'=>true]) }}
				{{ Form::file('transactions',['class'=>'form-control']) }}
			
				{{ Form::button('<i class="fa fa-upload"></i> Subir arquivo', ['class'=>'btn btn_up btn-primary', 'type'=>'submit']) }}
				{{ Form::close() }}
				@include('admin.partials.loader')
			</div>
			@if(Route::current()->getName() == 'admin.concorrentes.index')
				<div class="text-right col-md-4">
					{{ Form::open(['route'=>'admin.concorrentes.index', 'method'=>'get', 'class'=>'form-inline']) }}
					<span>Buscar por:</span>
					{{ Form::select('company_id', [''=>'Selecione empresa']+$companies, Input::get('company_id'), ['class'=>'form-control']) }}
					{{ Form::button('<i class="fa fa-search"></i> Buscar', ['class'=>'btn btn-primary', 'type'=>'submit']) }}
					{{ Form::close() }}
				</div>
			@endif
		</div>
		
	</div>
</div>